Parameters:

    EnvironmentName:
        Description: environmentname
        Type: String 
        
       
Resources:

  BastionSecurityGrp: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
        GroupDescription: allow ssh
        VpcId:
        Fn::ImportValue:
         !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
          
  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          Fn::Base64:
            Fn::Join:
              - ''
              - - "#!/bin/bash\n"
                - "yum -y --security update\n"
          
          
      ImageId: ami-04590e7389a6e577c
      KeyName: bastion-key
      SecurityGroups:
      - Ref: WebSecurityGrp
      InstanceType: t2.micro
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'          
          
  BastionAutoscalingGroup: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      VPCZoneIdentifier: 
      - Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB-NETS"      
    LaunchConfigurationName: 
      Ref: BastionLaunchConfig
    MinSize: "0"
    MaxSize: "1"
    TargetGroupARNs:
    - Ref: BastionTargetGroup