Parameters:
   EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String

    VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this
    Type: String
    Default: 10.0.0.0/16
    
    PublicSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
    
    PublicSubnet2CIDR:
    Type: String
    Default: 10.0.1.0/24
        
 PrivateSubnet1CIDR:
 Type: String
 Default: 10.0.2.0/24
        
 PrivateSubnet2CIDR:
 Type: String
 Default: 10.0.3.0/24
		
Resources:
  VPC:
    type: AWS::EC2::VPC
      Properties:
        CiderBlock: !Ref VpcCIDR
        EnableDnsHostname: true
        Tags:
            - Key: Name
              Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
            -Key: Name
            -Value: !Ref Environment
            
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGetewayAttachment
      Properties:
        InternetGatewayID: !Ref InternetGateway
        VpcId: !Ref VPC
        
  PublicSubnet1:
    Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 0, !GetAZ's '' ]
        CirderBlock: !Ref PrivateSubnet1CIDR
        MapPublicIpOnLaunch: false
        Tags: 
            -Key: Name
             Value: !Sub ${EnvironmentName} Public Subnet (AZ1)


  PublicSubnet2:
    Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 1, !GetAZ's '' ]
        CirderBlock: !Ref PrivateSubnet2CIDR
        MapPublicIpOnLaunch: false
        Tags: 
            -Key: Name
             Value: !Sub ${EnvironmentName} Public Subnet (AZ2) 
             
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 0, !GetAZ's '' ]
        CirderBlock: !Ref PrivateSubnet1CIDR
        MapPublicIpOnLaunch: false
        Tags: 
            -Key: Name
             Value: !Sub ${EnvironmentName} Private Subnet (AZ1)

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 1, !GetAZ's '' ]
        CirderBlock: !Ref PrivateSubnet1CIDR
        MapPublicIpOnLaunch: false
        Tags: 
            -Key: Name
             Value: !Sub ${EnvironmentName} Private Subnet (AZ2)
